# Generated by Django 5.0.4 on 2024-04-13 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('frequency', models.IntegerField(help_text='Frequency of data fetch in minutes')),
                ('last_fetched', models.DateTimeField(blank=True, help_text='Timestamp of the last successful fetch', null=True)),
            ],
        ),
    ]
