# Generated by Django 5.0.4 on 2024-04-13 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('prices', '0001_create_table_data_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('price_decimal', models.DecimalField(decimal_places=4, help_text='Normalized price of the currency', max_digits=19)),
                ('price_raw', models.CharField(help_text='Original format of the price', max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('block_no', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='prices.datasources')),
            ],
        ),
    ]
