# Generated by Django 5.0.4 on 2024-04-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_create_table_price_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerecords',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
